### ISSUE TITLE
Failed 8 out of 16 tests on Odroid XU4

### ISSUE THREAD

**Issue by zbonk** [RidgeRun/gst-interpipe#11]
I have compiled your gst-interpipe plugin on Odroid XU4 and after calling "make check" 8 out of 16 tests failed. You can see test logs here: https://pastebin.com/raw/ZbuAPakB

Additional information:
- GStreamer version: 1.8.3
- uname -a: Linux odroid 3.10.104 #1 SMP PREEMPT Tue Nov 29 10:18:41 UTC 2016 armv7l armv7l armv7l GNU/Linux
- gcc version: gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by fischer** [comment]
Thanks for the report.  We will get on of the engineers to take a look at the issues.

**Comment by mrneil** [comment]
@fischer @bperez241 Do you know if this issue was solved?

I'm seeing similar results on a machine with this info:

- GStreamer 1.8.3
- uname -a: Linux stream 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

Here's the [test-suite.log output](https://github.com/RidgeRun/gst-interpipe/files/1488518/test-suite.log) if it helps.

Thank you.

**Comment by dturing** [comment]
Is this project dead? 

I also see tests failing (9/16), on a simple desktop arch linux with gstreamer 1.14. 
[test-suite.log](https://github.com/RidgeRun/gst-interpipe/files/1998469/test-suite.log)

**Comment by dturing** [comment]
Thanks Todd, that's great to hear! I can see that the effort to get interpipe into gst-plugins-bad has stalled ([see gst bugzilla](https://bugzilla.gnome.org/show_bug.cgi?id=765820)), which is a shame because clearly it supports a very different use case than ipcpipeline (separating n-to-n pipelines in a single process vs 1-to-1 across process-- right?).

**Comment by jcaballeros** [comment]
Hi,

Interpipes share buffers within the same process.

I’m closing this issue because it has been inactive for a long time. Please feel free to reopen or open a new ticket if you encounter related issues.
