### ISSUE TITLE
Using Interpipes on Jetson TX-1 with NVMM

### ISSUE THREAD

**Issue by sperok** [RidgeRun/gst-interpipe#14]
Is there a trick to using Interpipes on a TX-1 with memory:NVMM for peak performance?

If I create two simple pipelines:

```
gstd> pipeline_create c1 nvcamerasrc name=nvcam1 sensor-id=2 ! capsfilter caps="video/x-raw(memory:NVMM),width=640,height=480,framerate=(fraction)30/1" ! interpipesink name=ipsink1

gstd> pipeline_create d1 interpipesrc listen-to=ipsink1 ! nvoverlaysink
gstd> pipeline_play c1
gstd> pipeline_play d1
```
tailing gstd shows the output below. I can get it to work by inserting nvvidconv on both sides of the interpipe, but that kills performance. I've tried using queues on both sides and all of the parameters from the camera example in the doc. 

```
gstd> pipeline_create c1 nvcamerasrc name=nvcam1 sensor-id=2 ! capsfilter caps="video/x-raw(memory:NVMM),width=640,height=480,framerate=(fraction)30/1" ! queue max-size-buffers=8 leaky=downstream ! interpipesink name=ipsink1 sync=true async=false
gstd> pipeline_create d1 interpipesrc listen-to=ipsink1 is-live=false allow-renegotiation=true enable-sync=false format=time ! queue max-size-buffers=11 leaky=downstream ! fakesink
```

Any other suggestions?

```
Available Sensor modes : 
3864 x 2174 FR=60.000000 CF=0x1009208a10 SensorModeType=4 CSIPixelBitDepth=10 DynPixelBitDepth=10
1932 x 1094 FR=120.000000 CF=0x1009208a10 SensorModeType=4 CSIPixelBitDepth=10 DynPixelBitDepth=10
1288 x 734 FR=120.000000 CF=0x1009208a10 SensorModeType=4 CSIPixelBitDepth=10 DynPixelBitDepth=10
1288 x 546 FR=240.000000 CF=0x1009208a10 SensorModeType=4 CSIPixelBitDepth=10 DynPixelBitDepth=10

NvCameraSrc: Trying To Set Default Camera Resolution. Selected sensorModeIndex = 0 WxH = 3864x2174 FrameRate = 60.000000 ...


(gstd:3747): GStreamer-CRITICAL **: gst_allocator_alloc: assertion '((params->align + 1) & params->align) == 0' failed

(gstd:3747): GStreamer-CRITICAL **: gst_memory_map: assertion 'mem != NULL' failed

(gstd:3747): GStreamer-CRITICAL **: gst_allocator_free: assertion 'memory != NULL' failed

(gstd:3747): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed

```

**Comment by josejich** [comment]
The problem that you are currently experiencing is due nvoverlaysink trying to get to the nvcamerasrc memory allocator in order to be able to register the buffers used from NVMM memory pool. Interpipes are currently not able to handle such queries (but it should be possible to implement), so on the current state  you must use nvvidconv to convert to normal memory to avoid triggering that query. Something like:
<pre>
gstd> pipeline_create c1 nvcamerasrc name=nvcam1 sensor-id=2 ! capsfilter caps="video/x-raw(memory:NVMM),width=640,height=480,framerate=(fraction)30/1" ! nvvidconv ! capsfilter caps="video/x-raw,width=640,height=480,framerate=(fraction)30/1" ! interpipesink name=ipsink1
</pre> 

And receive that stream on nvoverlaysink, hence you will take a hit on performance. I will mark this problem as an enhancement for future releases.

**Comment by sperok** [comment]
Thank you Jose. If the source for nvcamerasrc and nvoverlaysink were available I'd be happy to contribute this work. I spoke to some folks at NVidia about this specifically yesterday, but as of now this is proprietary.

**Comment by josejich** [comment]
No problem Spero, and yes; figuring out the actual the exact mechanism needed the memory requests and properly sharing using interpipes without having the actual code of those elements will be tricky (and probably somehow hackish) 

Have you checked GstCuda? 
http://developer.ridgerun.com/wiki/index.php?title=GstCUDA_-_Features_and_Limitations

We are actually able to share the NVMM buffers OR use a custom allocator to execute algorithms on the TX1 GPU. This might be more suitable for you depending on your requirements.

**Comment by josejich** [comment]
btw, in case of your particular pipeline you should be able to use a tee element instead of the interpipes to use the same nvcamerasrc for more than one sink in gstd:
<pre>
pipeline_create c1 nvcamerasrc name=nvcam1 sensor-id=2 ! capsfilter caps="video/x-raw(memory:NVMM),width=640,height=480,framerate=(fraction)30/1" ! queue max-size-buffers=8 leaky=downstream ! tee name=split ! fakesink split. ! fakesink
</pre>

**Comment by sperok** [comment]
Jose - Thank you, but our actual application is much more complex and matches the use case for interpipes. We are switching three different sensors and an audio stream, at least two overlays and at least three different output streams.

**Comment by jcaballeros** [comment]
Hi,

The latest version of GstInterpipe can pass NVMM buffers, check out this example [GTC 2020 demo](https://github.com/RidgeRun/gtc-2020-demo/blob/master/python-example/media-server.py). 

I’m closing this issue because it has been inactive for a long time. Please feel free to reopen if you still encounter a related issue with the latest source code.
