### ISSUE TITLE
enable-sync=true causes unnecessary buffer copies 

### ISSUE THREAD

**Issue by dgarbanzo** [RidgeRun/gst-interpipe#29]
In the gst_inter_pipe_src_push_buffer (GstInterPipeIListener * iface, GstBuffer * buffer, guint64 basetime) function, the buffer is converted to writable when enable-sync property is set true:

```
if (src->enable_sync) {
    guint64 difftime;

    buffer = gst_buffer_make_writable (buffer);
```

To compensate the timestamps it is not necessary to make the buffer writable. The fix is to remove the following line of the above code section: "buffer = gst_buffer_make_writable (buffer);"

Making the buffer writable causes unnecessary internal buffer copies if the incoming buffers are labeled as non-shareable.

**Comment by michaelgruner** [comment]
This will indeed make unnecessary copies if memory is not shareable. However we cannot remove it, because we are about to modify the timestamp. We can only do that if no one else is using the buffer.

**Comment by jcaballeros** [comment]
Hi,

The previous enable-sync=true property, now stream-sync=compensate-ts does not copy the full buffer memory when its made writable, instead, it just copies the buffer "metadata" because only the timestamp needs to be changed.

This is according to the documentation for [gst_buffer_make_writable](https://gstreamer.freedesktop.org/documentation/gstreamer/gstbuffer.html?gi-language=c#gst_buffer_make_writable).

I’m closing this issue because it has been inactive for a few months. Please feel free to reopen if you still encounter a related issue with the latest source code.
