### ISSUE TITLE
event_flush_* returns always Code 16: Event error

### ISSUE THREAD

**Issue by TopperBG** [RidgeRun/gst-interpipe#30]
Gstd version 0.6.3
Follow that [example](https://developer.ridgerun.com/wiki/index.php?title=GstInterpipe_-_Example_2:_Digital_Camera) 
I assume that event_flush_* are commands to start/stop empty buffer of pipeline. Is that correct?
But anyway how I use it - start when not using pipe or start when using pipe ( because on your site  they are used both ways https://developer.ridgerun.com/wiki/index.php?title=GStreamer_Daemon_-_Flush_start/Flush_stop)
 I'm still receive **Code 16: Event error**.

Do I need that flush for recording&streaming pipes and how to use it.

**Comment by jcaballeros** [comment]
Hi,

Flush start is used to empty the pipeline, and flush stop is used after a flush start so that the elements can accept new buffers. Flushing events are used when you need to ensure that the pipeline is empty, before pushing new buffers.

Can you share the pipeline to which you are sending the events? Also, can you share the gstd log for this error?

**Comment by jcaballeros** [comment]
Closing, feel free to reopen if necessary.
