### ISSUE TITLE
Simple pipeline rapidly out of memory on TX2

### ISSUE THREAD

**Issue by dangessner** [RidgeRun/gst-interpipe#45]
Hello, the following pipeline rapidly runs out of memory and is killed in approx 60 seconds when run on a Jetson TX2 dev kit that I believe is updated to most recent version:

gst-launch-1.0 videotestsrc ! interpipesink name=src interpipesrc listen-to=src ! xvimagesink

Adding "block=true" to interpipesrc stops the memory use and it runs indefinitely. Should block=true be required? Thanks!

**Comment by michaelgruner** [comment]
In this case you do need to block the internal interpipesrc queue. Here’s what’s going on:

1. The pipeline negotiates a given framerate (say 30/1 fps).
2. ximagesink will sync so that a buffer is displayed every 33.33ms
3. videotestsrc is working as a “non-live” source (will push as fast as it is allowed to).
4. Since the interpipesrc is not blocked, the interpipesink will always be able to push buffers.

Hence, videotestsrc is pushing as fast as it can while ximagesink is displaying at 30fps. Buffers accumulate in the interpipesrc.

**Comment by dvescovi1** [comment]
So if the property of videotestsrc is-live=true then there would not be a problem?

**Comment by dangessner** [comment]
Correct adding is-live=true also fixes this. Thanks for your help!

**Comment by prabathdj** [comment]
Is there a method to stop buffer accumulation when using v4l2src source ?
