### ISSUE TITLE
interpipe with udpsrc and udpsink

### ISSUE THREAD

**Issue by AlexandreLicinio** [RidgeRun/gst-interpipe#46]
Hi, 

I try interpipe to route several udp streams inputs (mpegts streams) to one udp output (udpsink).
No success for now :( Is interpipe able to route udp streams ?

2x udp inputs:
`pipeline_create p1 name=input1 udpsrc address=127.0.0.1 port=3000`
`pipeline_create p2 name=input2 udpsrc address=127.0.0.1 port=4000`

1x udp output:
`gstd> pipeline_create out1 interpipesrc name=output1 listen-to=input1 is-live=true allow-renegotiation=true enable-sync=true ! queue ! udpsink host=127.0.0.1 port=6000`

The error i get:
```
{
  "code" : 2,
  "description" : "Bad pipeline description",
  "response" : null
}
```

Thanks for helping

**Comment by jcaballeros** [comment]
Hi @AlexandreLicinio,

That gstd error appears when there is a syntax error. p1 and p2 have incorrect syntax, after the pipeline name, there is an unexpected statement name=input1 but gstd expects an element name there.

The error could also appear when one of the elements does not have a property being specified, for instance, the interpipesrc property enable-sync was removed since v1.0.7, then would lead to bad pipeline description if your installed interpipe version is v1.0.7 or above.

You may want to check the following gstd + gst-interpipe examples:

[GstInterpipe-Examples](https://developer.ridgerun.com/wiki/index.php?title=GstInterpipe_-_Examples)
[GStreamer_Daemon-Simple_Examples](https://developer.ridgerun.com/wiki/index.php?title=GStreamer_Daemon_-_Simple_Examples)

This other example shows gstd pipelines that use udpsink/udpsrc and interpipesink/interpipesrc:

`pipeline_create p0 videotestsrc is-live=true ! capsfilter caps=video/x-raw,width=320,height=240,framerate=30/1 ! queue ! x264enc ! queue ! mpegtsmux ! queue ! udpsink host=127.0.0.1 port=5000 sync=false`

`pipeline_create p1 udpsrc port=5000 address=127.0.0.1 do-timestamp=true ! capsfilter caps=video/mpegts,systemstream=true,packetsize=188 ! interpipesink name=input1 forward-events=true sync=false drop=true async=false enable-last-sample=false`

`pipeline_create p2 interpipesrc name=output1 listen-to=input1 format=time max-bytes=0 is-live=true allow-renegotiation=true stream-sync=compensate-ts ! capsfilter caps=video/mpegts,systemstream=true,packetsize=188 ! tsparse ! tsdemux ! capsfilter caps=video/x-h264,width=320,height=240,framerate=30/1 ! queue ! h264parse disable-passthrough=true ! avdec_h264 ! capsfilter caps=video/x-raw,width=320,height=240,framerate=30/1 ! queue ! autovideosink sync=false`

Hope this helps.

This doesn't seem to be a gst-interpipe issue, closing.
